name: Snakemake CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  snakemake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: snakemake
          environment-file: envs/environment.yml
          auto-activate-base: false

      - name: Run Snakemake
        shell: bash -l {0}
        run: |
          snakemake --cores 1 --dry-run